
###Get Products
GET https://localhost:5001/api/v1/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNKRGc5Y0g5TVl1S3VvU0dJWXhkRiJ9.eyJpc3MiOiJodHRwczovL250ZWdyYWwuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVmMGIwZTBkYjMyN2IzMDAxM2YxNDMyMSIsImF1ZCI6WyJkb3RuZXRlY29yZW1tZXJjZS5jb20vYXBpL3YxL3Byb2R1Y3RzIiwiaHR0cHM6Ly9udGVncmFsLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MDQ2NTExMTksImV4cCI6MTYwNDczNzUxOSwiYXpwIjoiTVAwQUZ0bzBxUDI5dHlHd3drcEFBRHR6TUg3VjR4bjUiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiZWRpdDpwcm9kdWN0cyIsInZpZXc6cHJvZHVjdHMiXX0.Q2K8ERs5zStn0P7NskJ5vMf2211sdeAzHm1XhrUwhWMesGpapi1wapJnpOpzJpLQCgV5ZW2z6xFdIHvERZcNw_ABguQ0j1NuT6AmJqBjWcMmdiAoBfy4ZavkvzVahZzcvjKgOZfz7VYmq-0CEKDwWEwWxrNGZV7wY-lZDQaWAM_C09oskV7bzTaOWAlpr5llHN2UDhaSLDHHd8PwvfH-svJyhMOpcrTZnUB7qiajrx-r93HaQN4e2wizw-90plwnD7UEm06zEtCvgUuqfr7VFoS8CHKyMZLf4-5MeMxaxf9yioz7JVKEFkkCDelUVz40XOeKRzkO4rRiSHca6tPzgg

###Get product by id
GET https://localhost:5001/api/v1/products/1

###Update Product
PUT https://localhost:5001/api/v1/products/11 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNKRGc5Y0g5TVl1S3VvU0dJWXhkRiJ9.eyJpc3MiOiJodHRwczovL250ZWdyYWwuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVmMGIwZTBkYjMyN2IzMDAxM2YxNDMyMSIsImF1ZCI6WyJkb3RuZXRlY29yZW1tZXJjZS5jb20vYXBpL3YxL3Byb2R1Y3RzIiwiaHR0cHM6Ly9udGVncmFsLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MDQ2NTA3NjYsImV4cCI6MTYwNDczNzE2NiwiYXpwIjoiTVAwQUZ0bzBxUDI5dHlHd3drcEFBRHR6TUg3VjR4bjUiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiZWRpdDpwcm9kdWN0cyIsInZpZXc6cHJvZHVjdHMiXX0.nmuwW3qOuP3iEdQhL11lOeyqOFSps5cuCgLWEW7-ZZy7H2nchJuO0qgEZEqMAQALgTHWFKL8_QXu8tBsia8zsxsdC-3FF1hAZ_keOgERoRWikkDds5fbOwR_A5NmoDqcEtRcP2mGCNRxmcMgBNbUx9AmZixdStv21PHbWD1NuLoXeQwA3bQERGSIpk-7CdMRswYKFfnpkOtgT2NoxRJ6Ay07Ds6TMgcx0Qbb9NEDTnCW2K0aIAHW7u2oREdYDdxOfHQ9bKWY_5WRYEJU-_vsrydv5_kFId-oDXMNdvr5RZap2p2Fae3K28lkweFotdOkoUuJL3pQoLhDjQe19GnrbA

{
  "id": 11,
  "name": "Yazzy jig",
  "category": "Power Tools",
  "description": "Yazzie sensible",
  "price": 25.00
}

###Add new Product
POST https://localhost:5001/api/v1/products HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNKRGc5Y0g5TVl1S3VvU0dJWXhkRiJ9.eyJpc3MiOiJodHRwczovL250ZWdyYWwuZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVmMGIwZTBkYjMyN2IzMDAxM2YxNDMyMSIsImF1ZCI6WyJkb3RuZXRlY29yZW1tZXJjZS5jb20vYXBpL3YxL3Byb2R1Y3RzIiwiaHR0cHM6Ly9udGVncmFsLmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE1OTYzNzk4NzEsImV4cCI6MTU5NjQ2NjI3MSwiYXpwIjoiTVAwQUZ0bzBxUDI5dHlHd3drcEFBRHR6TUg3VjR4bjUiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwicGVybWlzc2lvbnMiOlsiZWRpdDpwcm9kdWN0cyIsInZpZXc6cHJvZHVjdHMiXX0.Vi_qR4KVoYdRoLPhaaf7qSR4G0muweHdfSPkviPISsOdQMZtrzwN0sq6Y5Y3tWzHyGxXGXni7ye8BVKXZ98LuMf6arvHfcXVKTfk33iGqWjb3wyKiWUkJUWGyINlqQHm-bXbil4rYOUJFNXPEYWGFvONlbyUWnnL8TB6TloYu5BgnvDLEZiolWvJ2_6FZz4qzg0gDotBEYKUR3uUw1FoAlEC1Cc6w7hUUtU8f_rONdnqnBTsmjm8iZaQwNlc_q5giCIpRuwY99klVl_qe6jNL4VPW3aJCBnk_6NwwgUIamm5lIj45FP7fJczXLSGkdtAvt4eXlbhFjl52HdcLy7kQA

{
 "name": "Monkey Wrench",
 "category": "Hand Tools",
 "description": "I dont wanna be your monkey wrench",
 "price": 6.00
}